CREATE DATABASE locacarros;

USE locacarros;

CREATE TABLE numsei
(
	idEmpresa INT PRIMARY KEY IDENTITY,
	Nome       VARCHAR(100)	NOT NULL,
	
);
CREATE TABLE VEICULO
(
	idVeiculo INT PRIMARY KEY IDENTITY,
	idEmpresa INT FOREIGN KEY REFERENCES numsei(idEmpresa),
	
);
CREATE TABLE ALUGUEL
(
	idAluguel INT PRIMARY KEY IDENTITY,
	IdVeiculo INT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
);
CREATE TABLE CLIENTE
(
	idCliente INT PRIMARY KEY IDENTITY,
	Nome	VARCHAR(100) NOT NULL,
	CPF varchar(15),

);
CREATE TABLE MARCA
(
	idMarca INT PRIMARY KEY IDENTITY,
	Nome	VARCHAR(100) NOT NULL,

);
CREATE TABLE MODELOS
(
	idModelo INT PRIMARY KEY IDENTITY,
	idMarca  INT FOREIGN KEY REFERENCES MARCA(idMarca),
	Descrição varchar(100) not null,
	
);
